config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get '/about_us', to: 'static#about'
  get '/user_login', to: 'sessions#user_new'
  post '/user_login', to: 'sessions#create'
  get '/company_login', to: 'sessions#company_new'
  post '/company_login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :companies, except: [:index] do
    resources :posts do
      get '/new_email', to: 'posts#new_email'
      post '/send_email', to: 'posts#send_email'
    end
  end

  resources :users, except: [:index]
  get '/users/:id/matches', to: 'users#matches', as: :user_matches
  get '/posts', to: 'posts#all_posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :posts, dependent: :destroy
  validates :name, presence: { message: "Nombre es requerido" } 
  validates :email, presence: { message: "Email es requerido" } 
  validates :phone_number, presence: { message: "Un numero telefonico es requerido" } 
  validates :description, presence: { message: "Descripción es requerido" }
  validates :address, presence: { message: "Dirección es requerido" }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP, message: "El email introducido debe ser un email válido" },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_one_attached :avatar
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:new, :create]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        log_in_company @company
        format.html { redirect_to @company, notice: 'Compañía fue creada exitosamente.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Compañía fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Compañía fue destruida exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :email, :phone_number, :address, :description, :password, :password_confirmation, :avatar)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true, class: "left-align company form") do |form| %>
  <% if company.errors.any? %>
    <div>
      <b>
        <%= pluralize(@company.errors.count, "error", "errores") %> <%= (@company.errors.count && @company.errors.count > 1 ? "prohibieron" : "prohibio") %> crear la compañía:
      </b>
      <ul class="browser-default left-align">
        <% @company.errors.messages.each do |key, messages| %>
          <% messages.each do |message| %>
            <li class="red-text"><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row section">
    <div class="file-field field center-align">
      <div>
        <% if company.avatar.attached? %>
          <%= image_tag @company.avatar.variant(resize: '100x100'), size: "100x100", class: "circle" %>
        <% else %>
          <i class="large material-icons teal-text lighten-2">add_a_photo</i>
        <% end %>
        <%= form.file_field :avatar, accept:'image/*' %>
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text" placeholder="<%= company.avatar.attached? ? 'Cambiar logo' : 'Inserta un logo' %>">
      </div>
    </div>
    <div class="field">
      <%= form.label :nombre %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :numero %>
      <%= form.text_field :phone_number %>
    </div>

    <div class="field">
      <%= form.label :dirección %>
      <%= form.text_field :address %>
    </div>

    <div class="field">
      <%= form.label :descripción %>
      <%= form.text_area :description, class: "materialize-textarea" %>
    </div>
    <div class="field">
      <%= form.label :contraseña %>
      <%= form.password_field :password %>
    </div>
    <div class="field">
      <%= form.label :confirmar_contraseña %>
      <%= form.password_field :password_confirmation %>
    </div>
  </div>

  <div class="actions center-align">
    <%= form.submit "Submitir", class: "waves-effect waves-light btn green white-text" %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<%= content_for(:body_class, "edit") %>
<div class="grid">
  <% if !@company.avatar.attached? %> 
    <i class="large material-icons white-text default-avatar" alt="edit">edit</i>
  <% end %>
  <div class="profile-content white <%= !@company.avatar.attached? && 'bottom-attached' %>">
    <%= render 'form', company: @company %>

    <%= link_to 'Cancelar', @company, class: "btn-flat lighten-1 grey white-text" %>
    <p><%= link_to 'Borrar compañía', @company, method: :delete, 
                                             data: { confirm: 'Confirma que quiere borrar su cuenta?' }, 
                                             class: "btn-flat lighten-2 red white-text" %>
    </p>
  </div>
</div>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Address</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.email %></td>
        <td><%= company.phone_number %></td>
        <td><%= company.address %></td>
        <td><%= company.description %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<% content_for :body_class, "edit" %>
<div class="grid">
  <i class="large white-text material-icons default-avatar white-text" alt="edit">edit</i>
  <div class="profile-content white bottom-attached">
    <%= render 'form', company: @company %>
    <%= link_to t('Cancelar'), root_path, class: "btn-flat grey white-text waves-effect waves-light" %>
  </div>
</div>

app/views/companies/show.html.erb
<% content_for :body_class, "companies-background" %>

<% if notice %>
<div class="z-depth-1 card green lighten-5">
  <div class="card-content green-text left-align" style="border:1px solid green;">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<% end %>

<div class="grid">
  <% if @company.avatar.attached? %>
    <%= image_tag @company.avatar.variant(resize: '200x200'), size: "200x200", class: "circle company-avatar" %>
  <% else %>
    <i class="large material-icons default-avatar white-text">business</i>
  <% end %>

  <div class="profile-content white <%= !@company.avatar.attached? && 'bottom-attached' %>">
    <div class="top section">
      <h4><b><%= @company.name.capitalize %></b></h4>
      <p class="grey-text"><b><%= @company.address %></b></p>
      <p class="grey-text"><b><%= @company.email %></b></p>
      <p class="grey-text"><b><i><%= @company.phone_number %></i></b></p>
      <div class="center-align">
        <%= link_to "Posiciónes disponibles", company_posts_path(@company), class: "btn-flat blue lighten-1 white-text" %>
      </div>
    </div>

    <div class="divider"></div>
    <div class="section left-align white black-text light-padding">
      <div>
        <label>Un poco sobre la compañía:</label>
        <p><%= @company.description %></p>
      </div>
    </div>
    <% if current_user == @company %>
    <div class="divider"></div>
    <div>
      <p><%= link_to 'Crear nueva posición', new_company_post_path(@company), class: "btn-flat green white-text" %></p>
      <p><%= link_to 'Editar compañía', edit_company_path(@company), class: "btn-flat orange lighten-3 white-text" %></p>
    </div>
    <% end %>
  </div>
</div>