config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get '/about_us', to: 'static#about'
  get '/user_login', to: 'sessions#user_new'
  post '/user_login', to: 'sessions#create'
  get '/company_login', to: 'sessions#company_new'
  post '/company_login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :companies, except: [:index] do
    resources :posts do
      get '/new_email', to: 'posts#new_email'
      post '/send_email', to: 'posts#send_email'
    end
  end

  resources :users, except: [:index]
  get '/users/:id/matches', to: 'users#matches', as: :user_matches
  get '/posts', to: 'posts#all_posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :company

  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  validates :title, presence: { message: "Título es requerido" }
  validates :description, presence: { message: "Descripción es requerido" }
  validates :tag_ids, presence: { message: "Debe elegir al menos un interés" }

  def self.younger_job_types
    ['pasantia', 'trabajo de verano']
  end

  def self.older_job_types
    ['pasantia', 'part time', 'full time']
  end

  def self.all_job_types
    Post.younger_job_types + Post.older_job_types
  end

  def self.younger_jobs
    Post.select { |post| Post.younger_job_types.include?(post.job_type) }
  end
  
  def self.older_jobs
    Post.select { |post| Post.older_job_types.include?(post.job_type) }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :update, :destroy]

  def all_posts
    if logged_in_as_user?
      @posts = Post
                .includes(:company)
                .where(id: current_user.allowed_posts_by_job_type)
    elsif logged_in_as_company?
      @posts = current_user.posts
    end
  end

  # GET /posts
  # GET /posts.json
  def index
    @company = Company.includes(:posts).find(params[:company_id])
    if logged_in_as_user?
      @posts = @company.posts.where(id: current_user.allowed_posts_by_job_type)
    else
      @posts = @company.posts
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @company = Company.includes(:posts).find(params[:company_id])
    @post = @company.posts.new
    @tags = Tag.all
  end

  # GET /posts/1/edit
  def edit
    @company = Company.includes(:posts).find(params[:company_id])
    @post = @company.posts.includes(:tags).find(params[:id])
    @tags = Tag.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @company = Company.includes(:posts).find(params[:company_id])
    @post = @company.posts.new(post_params)
    @tags = Tag.all

    respond_to do |format|
      if @post.save
        format.html { redirect_to [@company, @post], notice: 'Posición fue creado exitosamente' }
        format.json { render :show, status: :created, location: [@company, @post] }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Posición fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def new_email
    @user = current_user
    @post = Post.includes(:company).find(params[:post_id])
    @company = @post.company
  end

  def send_email
    @user = current_user
    @post = Post.includes(:company).find(params[:post_id])
    @company = @post.company
    UserMailer.with(
      user: @user,
      post: @post,
      company: @company,
      subject: params[:subject],
      body: params[:body],
    ).interested_email.deliver_now


    redirect_to [@company, @post], notice: 'Tu correo electrónico fue enviado con éxito'
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Posición fue destruido exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @company = Company.includes(:posts).find(params[:company_id])
      @post = @company.posts.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :company_id, :job_type, tag_ids: [])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, url: [@company, @company.posts.build], class: "left-align post form", local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <b>
        <%= pluralize(@post.errors.count, "error", "errores") %> <%= (@post.errors.count && @post.errors.count > 1 ? "prohibieron" : "prohibio") %> crear la posición:
      </b>
      <ul class="browser-default left-align">
        <% @post.errors.messages.each do |key, messages| %>
          <% messages.each do |message| %>
            <li class="red-text"><%= message %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :título %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :descripción %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :tipo_de_empleo %>
    <%= select(:post, :job_type, [['part time', 'part time'], ['full time', 'full time'], ['pasantia', 'pasantia'], ['trabajo de verano', 'trabajo de verano']]) %>
  </div>

  <div class="field left-align">
    <strong>Intereses:</strong><br />
    <div class="row">
      <% @tags.each do |tag| %>
        <div class="col s6">
          <label>
            <%= form.check_box :tag_ids, { id: "#{tag.name}", class: "filled-in", checked: @post.tags.include?(tag), multiple: true, value: tag.id }, tag.id.to_s, false %>
            <span><%= tag.name %></span>
          </label>
        </div>
      <% end %>
    </div>
  </div>

  <div class="actions center-align">
    <%= form.submit "Submitir", class: "waves-effect waves-light btn green white-text" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<div class="collection left-align">
  <% @posts.each do |post| %>
    <div class="collection-item">
      <span class="new badge <%= post.job_type %>" data-badge-caption="<%= post.job_type %>"></span>
      <span class="align-icon-with-text">
        <b><%= link_to post.title, company_post_path(post.company, post) %></b>
        <% if logged_in_as_user? && current_user.matches.include?(post) %>
          <i class="tiny material-icons yellow-text" alt="star">star</i>
        <% end %>
      </span>
      <% if current_user == post.company %>
        <td><%= link_to 'Editar', edit_company_post_path(post.company, post) %></td>
        <td><%= link_to 'Borrar', [post.company, post], method: :delete,  data: { confirm: 'Confirma que quiere borrar esta posición?' }, class: "red-text" %></td>
      <% end %>
      <p class="truncate"><%= post.description %></p>
      <div class="divider"></div>
      <p>
        <% post.tags.each do |tag| %>
          <div class="chip blue lighten-1 white-text">
            <%= tag.name %>
          </div>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/all_posts.html.erb
<% content_for :body_class, "all-posts-background" %>


<% if @posts.empty? %>
  <h5 class="white-text">No hay mas posiciónes disponibles</h5>
<% else %>
  <h5 class="white-text">Todos los trabajos disponibles</h5>
  <%= render partial: 'posts', object: @posts %>
<% end %>

app/views/posts/edit.html.erb
<%= content_for(:body_class, "edit") %>
<div class="grid">
  <i class="large material-icons default-avatar white-text" alt="edit">edit</i>
  <div class="profile-content white bottom-attached">
    <%= render 'form', post: @post %>
    <%= link_to 'Cancelar', company_post_path(@post.company, @post), class: "btn-flat lighten-1 grey white-text" %>
    <p>
      <%= link_to 'Borrar posición', [@post.company, @post], method: :delete, 
                                               data: { confirm: 'Confirma que quiere borrar esta posición?' }, 
                                               class: "btn-flat lighten-2 red white-text" %>
    </p>
  </div>
</div>

app/views/posts/index.html.erb
<% content_for :body_class, "all-posts-background" %>


<% if @posts.empty? %>
  <h5 class="white-text">No hay mas posiciónes disponibles</h5>
<% else %>
  <h5 class="white-text">Todos los trabajos disponibles</h5>
  <%= render partial: 'posts', object: @posts %>
<% end %>

app/views/posts/new.html.erb
<%= content_for(:body_class, "edit") %>
<div class="grid">
  <i class="large material-icons default-avatar white-text" alt="edit">edit</i>
  <div class="profile-content white bottom-attached">
    <%= render 'form', post: @post %>
    <%= link_to 'Back', :back, class: "btn-flat grey white-text waves-effect waves-light" %>
  </div>
</div>

app/views/posts/new_email.html.erb
<%= content_for(:body_class, "edit") %>
<div class="grid">
  <i class="large material-icons default-avatar white-text" alt="email">email</i>
  <div class="profile-content white bottom-attached">
    <div class="top section email">
      <% if @user.resume.attached? %>
        <h6 class="lighten-1 blue-text"><b>Su currículum se adjuntará automáticamente al correo electrónico.</b></h6>
      <% end %>
    </div>
  
    <div class="section left-align">
      <%= form_tag(company_post_send_email_path(@post.company, @post), method: "post") do %>
        <%= label_tag(:subject, "Subjeto") %>
        <%= text_field_tag(:subject, "", class: "field", required: true) %><br />
        <%= label_tag(:cuerpo, "Cuerpo") %>
        <%= text_area_tag(:body, "", class: "materialize-textarea", required: true) %>
        <div class="center-align">
          <button class="btn waves-effect waves-light lighten-1 blue white-text" type="submit" name="action">
            <i class="material-icons right" style="margin-left:0;">send</i>
            <%= submit_tag("Enviar", class: "white-text") %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% content_for :body_class, "users-background" %>

<% if notice %>
<div class="z-depth-1 card green lighten-5">
  <div class="card-content green-text left-align" style="border:1px solid green;">
    <p id="notice"><%= notice %></p>
  </div>
</div>
<% end %>

<div class="grid">


  <i class="large material-icons default-avatar business-center white-text" alt="business_center">business_center</i>
  <div class="profile-content white bottom-attached">

    <div class="top section">
      <h4><b><%= @post.title.capitalize %></b></h4>
      <p class="grey-text"><b><%= @post.job_type %></b></p>
      <p class="grey-text"><i>Publicado por: <b><%= link_to @post.company.name.capitalize, company_path(@post.company) %></b></i></p>
    </div>

    <div class="divider"></div>
    <div class="section left-align white black-text light-padding">
      <div>
        <label>Un poco sobre la posición:</label>
        <p>
          <%= @post.description %>
        </p>
      </div>
    </div>

    <div class="divider"></div>
    <div class="section left-align light-padding">
      <label>Categorías:</label>
      <div class="chips-container">
        <% @post.tags.each do |tag| %>
          <div class="chip blue lighten-1 white-text">
            <%= tag.name %>
          </div>
        <% end %>
      </div>
    </div>

    <% if logged_in_as_user? %>
      <div class="divider"></div>
      <div class="section left-align light-padding">
        <label>Si te interesa la posición, puedes contactar la compañía:</label>
        <p class="center-align">
          <%= link_to 'Me Interesa!', company_post_new_email_path(@post.company, @post), class: "btn green waves-effect waves-light" %>
        </p>
      </div>
    <% end %>

    <% if current_user == @post.company %>
      <div class="divider"></div>
      <div>
        <p><%= link_to 'Editar Posición', edit_company_post_path(@post.company, @post), class: "btn-flat orange lighten-1 white-text" %></p>
      </div>
    <% end %>

    <%= link_to 'Atrás', :back, class: "btn-flat lighten-1 grey white-text" %>

  </div>


</div>