config/routes.rb
Rails.application.routes.draw do
  root 'static#welcome'
  get '/about_us', to: 'static#about'
  get '/user_login', to: 'sessions#user_new'
  post '/user_login', to: 'sessions#create'
  get '/company_login', to: 'sessions#company_new'
  post '/company_login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :companies, except: [:index] do
    resources :posts do
      get '/new_email', to: 'posts#new_email'
      post '/send_email', to: 'posts#send_email'
    end
  end

  resources :users, except: [:index]
  get '/users/:id/matches', to: 'users#matches', as: :user_matches
  get '/posts', to: 'posts#all_posts'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YoungerJob</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" type="text/javascript"></script>
    <!-- MaterializeCSS Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- MaterializeCSS Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0">
  </head>

  <body>
    <nav>
      <div class="nav-wrapper white">
        <ul class="nav-items">
            <% if logged_in? %>
              <% if logged_in_as_user? %>
                <li>
                  <%= link_to user_path(current_user) do %>
                    <i class="material-icons green-text darken-4" alt="person">person</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to user_matches_path(current_user) do %>
                    <i class="material-icons yellow-text" alt="star">star</i>
                  <% end %>
                </li>
              <% elsif logged_in_as_company? %>
                <li>
                  <%= link_to company_path(current_user) do %>
                    <i class="material-icons orange-text darken-4" alt="person">person</i>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_company_post_path(current_user) do %>
                    <i class="material-icons green-text" alt="add">add</i>
                  <% end %>
                </li>
              <% end%>
              <li>
                <%= link_to(posts_path) do %>
                  <i class="material-icons blue-text darken-4" alt="list">list</i>
                <% end %>
              </li>
              <% end %>
              <li>
                <%= link_to about_us_path, class: "darken-1 orange-text" do %>
                  <i class="material-icons" alt="about us">face</i>
                <% end %>
              </li>
              <% if logged_in? %>
                <li>
                  <%= link_to logout_path, class: "black-text align-icon-with-text" do %>
                    Salir <i class="material-icons" alt="exit">exit_to_app</i>
                  <% end %>
                </li>
              <% end %>
          </ul>
        </div>
      </nav>
    <div class="container <%= yield (:body_class) %>">
      <div class="row center-align">
        <div class="col s12 m10 offset-m1 l8 offset-l2">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>